name: letify

packages:
  - lib/*
  - packages/*

scripts:
  analyze:
    exec: dart analyze .

  generate:
    run: melos exec -c 1 --depends-on="build_runner" --flutter --  "dart run build_runner build --delete-conflicting-outputs"
    description: Build all generated files for Dart packages in this project.

  generate:flutter:
    run: melos exec -c 1 --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Build all generated files for Flutter packages in this project.

  test:flutter:
    run: melos exec --dir-exists="test" -c 1 --fail-fast -- "flutter test"
    description: Run Flutter tests for a specific package in this project.
    packageFilters:
      flutter: true
      dirExists: test

  test:
    run: melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.
