name: github_viewer
description: "Mobile app demonstrating Github API usage"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  common:
    path: packages/common
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  go_router_navigator:
    path: packages/go_router_navigator
  https_repository:
    path: packages/https_repository
  injectable: ^2.4.2
  main_viewer:
    path: packages/main_viewer
  navigator:
    path: packages/navigator

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  melos: ^6.0.0
  patrol: ^3.7.2

flutter:
  uses-material-design: true
