name: github_viewer
description: "Mobile app demonstrating Github API usage"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  common:
    path: packages/common
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  injectable: ^2.4.2
  main_viewer:
    path: packages/main_viewer

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
