name: https_repository
description: "Package responsible for connecting with backend using https and http"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  common:
    path: ../common
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  http: ^1.2.1
  injectable: ^2.4.2
  main_viewer:
    path: ../main_viewer

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
flutter: null
