name: go_router_navigator
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  common:
    path: ../common
  flutter:
    sdk: flutter
  go_router: ^14.1.3
  injectable: ^2.4.2
  main_viewer:
    path: ../main_viewer
  navigator:
    path: ../navigator

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.0
  injectable_generator: ^2.6.1

flutter: null
