name: main_viewer
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  animate_do: ^3.3.4
  animated_loading_border: ^0.0.2
  async: ^2.11.0
  bloc: ^8.1.4
  common:
    path: ../common
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  injectable: ^2.4.2
  intl: ^0.18.1
  navigator:
    path: ../navigator

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  mockito: ^5.4.4

flutter: null
